### ISSUE TITLE
Neo Keyboard Layout and Jupyter

### ISSUE THREAD

**Issue by unic0rned** [hmeine/MeVisLab-CLI#1]
Hey HMeine,

sorry dass ich es über diesen Weg versuche aber es gibt leider keine privaten Nachrichten bei GitHub ;)

Habe gesehen, dass du vor 4 Jahren was zu Jupyter und Neo geschrieben hast.

Leider gehen bei mir die Shortcuts für = und + nicht in Jupyter. Das ist super schade, da Neo ja genau fürs programmieren so geil ist. Hast du da eine Lösung gefunden?
Würde es echt gerne benutzen :)

Liebe Grüße von einem Neo User.

unic0rned

**Comment by hmeine** [comment]
Sorry, ist mir untergegangen. Hat sich das erledigt?

Ich habe gerade erst das gleiche Problem mit Firefox auf macOS bemerkt. Mit Safari habe ich das Problem nicht. (Bei Google Docs habe ich aber z.B. weniger Probleme mit Firefox als mit Chrome.)
